# Custom nav
nav:
  title: "Die antwort"

favicon: "/source/images/favicon.ico"

# Custom background
background:
  color: "#eff0f6"
  image: ""

# Social media
social:
  GitHub: https://github.com/zhijielee
  Twitter: https://twitter.com/zhijie1998
  Instagram: https://www.instagram.com/zhijie_li1998
  Zhihu: https://www.zhihu.com/people/die-antwort

# Custom footer
mail: i@zhijie.li
copyright: All rights reserved @Die antwort

# Custom menu. You can specific the path or the card style (only useful for category page).
# Two kinds of card style: 'project-card', 'article-card',
# Never mind the name.
menu:
  # Project:
  #   path: /categories/Projects
  #   card: project-card
  # Stuffs:
  #   path: /tags/Stuffs
  #   card: article-card
  Home: /
  Archive: archives
  Tag: tags
  Categories: categories
  About: about
  Search: search

# Specific default categories or tags of home page.
# Post which belongs to `category` or `tag` and don't belongs to `except_category` or `except_tag` will be filtered.
home:
  # set card style of home page
  # category: python
  # tag: 算法
  # except_category: 树
  # except_tag:
  #   - 总结
  #   - css

card_style:
  home: project-card
  archive: article-card
  tag: article-card
  category: article-card

# category page
category_generator:
  category_per_page: 3
  post_per_category: 3

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Beian ICP and gongan information for Chinese users.
# beian:
#   enable: true
#   icp: 皖ICP备2021006467号-2

# Search
# search:
#   path: search.xml
#   field: post
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # if there are no result
